# Generated by Django 3.2.8 on 2021-10-20 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('major', models.CharField(max_length=128)),
                ('grade', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=1, null=True)),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.book')),
                ('no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.student')),
            ],
            options={
                'db_table': 'rentals',
            },
        ),
    ]
